import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { AlertCircle, AlertTriangle, CheckCircle2, Info, Lock } from 'lucide-react';
import { integrityApi } from '../../api/integrity';
import { useNavigate } from 'react-router-dom';

export const IntegrityView: React.FC = () => {
  const [severity,setSeverity]=useState(''); const [page,setPage]=useState(1); const navigate=useNavigate();
  const query=useQuery({queryKey:['integrity',severity,page],queryFn:()=>integrityApi.list(severity,page)});
  const meta=query.data?.meta; const findings=query.data?.data||[];
  return <div dir="rtl" className="mx-auto max-w-6xl space-y-5 p-4 sm:p-6"><header><div className="flex items-center gap-2 text-indigo-700"><Lock className="h-4 w-4"/><span className="text-xs font-black">فقط‌خواندنی</span></div><h1 className="mt-2 text-2xl font-black text-slate-900">پایش یکپارچگی عملیات</h1><p className="mt-1 text-xs text-slate-500">این صفحه فقط ناسازگاری‌ها را گزارش می‌کند و هیچ اصلاح خودکاری انجام نمی‌دهد.</p></header><div className="grid grid-cols-3 gap-3"><Summary label="بحرانی" count={meta?.summary.critical||0} tone="rose"/><Summary label="هشدار" count={meta?.summary.warning||0} tone="amber"/><Summary label="اطلاعات" count={meta?.summary.info||0} tone="sky"/></div><div className="rounded-2xl border border-slate-200 bg-white p-3"><select value={severity} onChange={e=>{setSeverity(e.target.value);setPage(1)}} className="rounded-xl border border-slate-200 px-3 py-2 text-xs"><option value="">همه شدت‌ها</option><option value="critical">بحرانی</option><option value="warning">هشدار</option><option value="info">اطلاعات</option></select></div><section className="space-y-2">{query.isLoading&&<p className="p-8 text-center text-xs text-slate-500">در حال اجرای بررسی‌ها…</p>}{findings.map((item,index)=><button key={`${item.code}-${item.type}-${item.id}-${index}`} onClick={()=>navigate(item.link)} className="flex w-full items-start gap-3 rounded-2xl border border-slate-200 bg-white p-4 text-right hover:border-indigo-200">{item.severity==='critical'?<AlertCircle className="mt-0.5 h-5 w-5 shrink-0 text-rose-600"/>:item.severity==='warning'?<AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-amber-600"/>:<Info className="mt-0.5 h-5 w-5 shrink-0 text-sky-600"/>}<div><p className="text-xs font-black text-slate-800">{item.message}</p><p className="mt-1 font-mono text-[10px] text-slate-400">{item.code} · {item.type} #{item.id}</p></div></button>)}{!query.isLoading&&!findings.length&&<div className="rounded-3xl border border-emerald-200 bg-emerald-50 p-10 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-emerald-600"/><p className="mt-2 text-sm font-black text-emerald-800">موردی در این سطح پیدا نشد.</p></div>}</section>{meta&&meta.last_page>1&&<div className="flex justify-center gap-2"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} className="rounded-lg border px-3 py-1 text-xs disabled:opacity-40">قبلی</button><span className="px-2 py-1 text-xs">{page.toLocaleString('fa-IR')} / {meta.last_page.toLocaleString('fa-IR')}</span><button disabled={page>=meta.last_page} onClick={()=>setPage(p=>p+1)} className="rounded-lg border px-3 py-1 text-xs disabled:opacity-40">بعدی</button></div>}</div>;
};
const Summary=({label,count,tone}:{label:string;count:number;tone:'rose'|'amber'|'sky'})=><div className={`rounded-2xl border p-4 ${tone==='rose'?'border-rose-200 bg-rose-50 text-rose-800':tone==='amber'?'border-amber-200 bg-amber-50 text-amber-800':'border-sky-200 bg-sky-50 text-sky-800'}`}><p className="text-[10px] font-bold">{label}</p><p className="mt-1 text-xl font-black">{count.toLocaleString('fa-IR')}</p></div>;
export default IntegrityView;
